const BASE_URL = "https://hvacthermal.com";

const calculatorPaths = [
  "/calculator/btu-calculator",
  "/calculator/boiler-size-calculator",
  "/calculator/heat-pump-size-calculator",
];

const guidePaths = [
  "/guides/nest-thermostat-review-uk",
  "/guides/hive-thermostat-review-uk",
  "/guides/best-smart-thermostats-uk",
  "/guides/underfloor-heating-cost-uk",
  "/guides/how-to-reset-a-boiler",
  "/guides/immersion-heater-vs-boiler",
  "/guides/hot-water-cylinder-uk",
  "/guides/boiler-timer-controls-uk",
  "/guides/boiler-vs-heat-pump-cost",
  "/guides/best-boiler-brands-uk",
  "/guides/combi-boiler-low-hot-water-pressure",
  "/guides/no-central-heating-but-hot-water",
  "/guides/boiler-clicking-noise",
  "/guides/bleeding-radiator-no-water",
  "/guides/cold-house-uk",
  "/guides/drayton-thermostat-review-uk",
  "/guides/tado-thermostat-review-uk",
  "/guides/viessmann-boiler-review-uk",
  "/guides/boiler-inhibitor-uk",
  "/guides/wet-underfloor-heating-uk",
  "/guides/boiler-pressure-keeps-dropping",
  "/guides/how-to-increase-boiler-pressure",
  "/guides/combi-boiler-no-heating",
  "/guides/boiler-keeps-switching-off",
  "/guides/frozen-condensate-pipe",
  "/guides/boiler-making-banging-noise",
  "/guides/radiator-cold-at-bottom",
  "/guides/radiator-cold-at-top",
  "/guides/how-to-balance-radiators",
  "/guides/central-heating-sludge",
  "/guides/boiler-efficiency-ratings",
  "/guides/condensing-boiler-uk",
  "/guides/boiler-replacement-cost-uk",
  "/guides/worcester-bosch-vs-vaillant",
  "/guides/boiler-carbon-monoxide",
  "/guides/heat-pump-running-costs-uk",
  "/guides/hydrogen-boiler-uk",
  "/guides/electric-boiler-uk",
  "/guides/oil-boiler-uk",
  "/guides/lpg-boiler-uk",
  "/guides/boiler-not-working",
  "/guides/no-hot-water",
  "/guides/boiler-leaking",
  "/guides/pilot-light-keeps-going-out",
  "/guides/boiler-lockout",
  "/guides/thermostatic-radiator-valves",
  "/guides/power-flush-central-heating",
  "/guides/magnetic-filter-boiler",
  "/guides/boiler-service-what-to-expect",
  "/guides/cold-radiators-hot-boiler",
  "/guides/boiler-installation-uk",
  "/guides/boiler-installation-time-uk",
  "/guides/worcester-bosch-boiler-review",
  "/guides/vaillant-boiler-review",
  "/guides/baxi-boiler-review",
  "/guides/ideal-boiler-review",
  "/guides/boiler-grant-uk",
  "/guides/eco4-scheme-uk",
  "/guides/gas-safe-engineer-uk",
  "/guides/central-heating-system-types-uk",
  "/guides/boiler-warranty-uk",
  "/guides/smart-thermostat-uk",
  "/guides/how-to-turn-off-a-boiler",
  "/guides/boiler-flue-regulations-uk",
  "/guides/how-to-drain-central-heating-system",
  "/guides/radiator-not-heating-up",
  "/guides/boiler-size-calculator-uk",
  "/guides/heat-pump-size-calculator-uk",
  "/guides/boiler-kw-calculator",
  "/guides/air-source-heat-pump-calculator-uk",
  "/guides/what-size-boiler-do-i-need",
  "/guides/how-many-btu-do-i-need",
  "/guides/what-size-heat-pump-do-i-need",
  "/guides/what-size-air-conditioner-do-i-need",
  "/guides/combi-boiler-vs-system-boiler",
  "/guides/heat-pump-vs-gas-boiler",
  "/guides/heat-pump-cost-uk",
  "/guides/what-is-seer-rating",
  "/guides/how-to-reduce-heating-bills",
  "/guides/what-size-radiators-do-i-need",
  "/guides/how-long-does-a-boiler-last",
  "/guides/new-boiler-cost-uk",
  "/guides/how-to-repressurise-a-boiler",
  "/guides/what-temperature-should-my-boiler-be-set-to",
  "/guides/boiler-service-cost-uk",
  "/guides/why-is-my-boiler-losing-pressure",
  "/guides/how-often-should-a-boiler-be-serviced",
  "/guides/boiler-making-noise",
  "/guides/what-is-a-combi-boiler",
  "/guides/boiler-error-codes",
  "/guides/central-heating-not-working",
  "/guides/when-should-i-replace-my-boiler",
  "/guides/boiler-cover-uk",
  "/guides/how-to-save-money-on-heating-bills",
  "/guides/boiler-pressure-too-high",
  "/guides/what-is-a-system-boiler",
  "/guides/gas-boiler-ban-uk",
  "/guides/home-energy-efficiency-uk",
  "/guides/underfloor-heating-vs-radiators",
];

export default function sitemap() {
  const homepage = {
    url: BASE_URL,
    lastModified: new Date(),
    changeFrequency: "weekly",
    priority: 1.0,
  };

  const guidesIndex = {
    url: `${BASE_URL}/guides`,
    lastModified: new Date(),
    changeFrequency: "weekly",
    priority: 0.9,
  };

  const calculators = calculatorPaths.map((path) => ({
    url: `${BASE_URL}${path}`,
    lastModified: new Date(),
    changeFrequency: "weekly",
    priority: 0.9,
  }));

  const guides = guidePaths.map((path) => ({
    url: `${BASE_URL}${path}`,
    lastModified: new Date(),
    changeFrequency: "weekly",
    priority: 0.8,
  }));

  return [homepage, guidesIndex, ...calculators, ...guides];
}
